// <auto-generated />
using System;
using EC.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EC.Infrastructure.Migrations
{
    [DbContext(typeof(EcDbContext))]
    [Migration("20251218105240_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EC.Domain.Data.Models.Dogadjaj", b =>
                {
                    b.Property<Guid>("IdDogadjaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumDogadjaja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventCenterID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdMape")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NazivDogadjaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisDogadja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusDogadjaja")
                        .HasColumnType("int");

                    b.Property<DateTime>("SysDtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDtUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDogadjaja");

                    b.HasIndex("EventCenterID");

                    b.HasIndex("IdMape");

                    b.ToTable("Dogadjaji");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.EventCenter", b =>
                {
                    b.Property<Guid>("EventCenterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAdresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktTelefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDtUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("EventCenterID");

                    b.ToTable("EventCentri");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.Gost", b =>
                {
                    b.Property<Guid>("IdGosta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDogadjaja")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InicijalSrednjegImena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDtUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("IdGosta");

                    b.HasIndex("IdDogadjaja");

                    b.ToTable("Gosti");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.MapaSedenja", b =>
                {
                    b.Property<Guid>("IdMape")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventCenterID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<string>("NazivMape")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RasporedJSON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDtUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("IdMape");

                    b.HasIndex("EventCenterID");

                    b.ToTable("MapeSedenja");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.Rezervacija", b =>
                {
                    b.Property<Guid>("IdRezervacije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumRezervacije")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdGosta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdGrupeKojaJeUsla")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdStolice")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SysDtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDtUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("IdRezervacije");

                    b.HasIndex("IdGosta");

                    b.HasIndex("IdStolice");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.Sto", b =>
                {
                    b.Property<Guid>("IdStola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojStola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdDogadjaja")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTemplejtaStola")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KapacitetStola")
                        .HasColumnType("int");

                    b.Property<int>("OblikStola")
                        .HasColumnType("int");

                    b.Property<double>("Rotacija")
                        .HasColumnType("float");

                    b.Property<DateTime>("SysDtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDtUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("XKordinata")
                        .HasColumnType("float");

                    b.Property<double>("YKordinata")
                        .HasColumnType("float");

                    b.HasKey("IdStola");

                    b.HasIndex("IdDogadjaja");

                    b.HasIndex("IdTemplejtaStola");

                    b.ToTable("Stolovi");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.Stolica", b =>
                {
                    b.Property<Guid>("IdStolice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojStolice")
                        .HasColumnType("int");

                    b.Property<Guid>("IdStola")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTemplejtaStolice")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PozicijaX")
                        .HasColumnType("float");

                    b.Property<double>("PozicijaY")
                        .HasColumnType("float");

                    b.Property<double>("Pravac")
                        .HasColumnType("float");

                    b.Property<DateTime>("SysDtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDtUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Zauzeta")
                        .HasColumnType("bit");

                    b.HasKey("IdStolice");

                    b.HasIndex("IdStola");

                    b.HasIndex("IdTemplejtaStolice");

                    b.ToTable("Stolice");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.Totem", b =>
                {
                    b.Property<Guid>("IdTotema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<Guid>("EventCenterID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdDogadjaja")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDtUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("IdTotema");

                    b.HasIndex("EventCenterID");

                    b.HasIndex("IdDogadjaja");

                    b.ToTable("Totemi");
                });

            modelBuilder.Entity("EC.Domain.Templates.TemplateStola", b =>
                {
                    b.Property<Guid>("IdTemplejtaStola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojStola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdMape")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KapacitetStola")
                        .HasColumnType("int");

                    b.Property<int>("OblikStola")
                        .HasColumnType("int");

                    b.Property<double>("Rotacija")
                        .HasColumnType("float");

                    b.Property<DateTime>("SysDtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDtUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("XKordinata")
                        .HasColumnType("float");

                    b.Property<double>("YKordinata")
                        .HasColumnType("float");

                    b.HasKey("IdTemplejtaStola");

                    b.HasIndex("IdMape");

                    b.ToTable("TemplateoviStolova");
                });

            modelBuilder.Entity("EC.Domain.Templates.TemplateStolice", b =>
                {
                    b.Property<Guid>("IdTemplejtaStolice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojStolice")
                        .HasColumnType("int");

                    b.Property<Guid>("IdTemplejtaStola")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PozicijaX")
                        .HasColumnType("float");

                    b.Property<double>("PozicijaY")
                        .HasColumnType("float");

                    b.Property<double>("Pravac")
                        .HasColumnType("float");

                    b.Property<DateTime>("SysDtCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SysDtUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Zauzeta")
                        .HasColumnType("bit");

                    b.HasKey("IdTemplejtaStolice");

                    b.HasIndex("IdTemplejtaStola");

                    b.ToTable("TemplateoviStolica");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.Dogadjaj", b =>
                {
                    b.HasOne("EC.Domain.Data.Models.EventCenter", "EventCentar")
                        .WithMany()
                        .HasForeignKey("EventCenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EC.Domain.Data.Models.MapaSedenja", "MapaSedenja")
                        .WithMany()
                        .HasForeignKey("IdMape");

                    b.Navigation("EventCentar");

                    b.Navigation("MapaSedenja");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.Gost", b =>
                {
                    b.HasOne("EC.Domain.Data.Models.Dogadjaj", "Dogadjaj")
                        .WithMany()
                        .HasForeignKey("IdDogadjaja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dogadjaj");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.MapaSedenja", b =>
                {
                    b.HasOne("EC.Domain.Data.Models.EventCenter", "EventCenter")
                        .WithMany()
                        .HasForeignKey("EventCenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventCenter");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.Rezervacija", b =>
                {
                    b.HasOne("EC.Domain.Data.Models.Gost", "Gost")
                        .WithMany()
                        .HasForeignKey("IdGosta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EC.Domain.Data.Models.Stolica", "Stolica")
                        .WithMany()
                        .HasForeignKey("IdStolice")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Gost");

                    b.Navigation("Stolica");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.Sto", b =>
                {
                    b.HasOne("EC.Domain.Data.Models.Dogadjaj", "Dogadjaj")
                        .WithMany()
                        .HasForeignKey("IdDogadjaja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EC.Domain.Templates.TemplateStola", "TemplateStola")
                        .WithMany()
                        .HasForeignKey("IdTemplejtaStola");

                    b.Navigation("Dogadjaj");

                    b.Navigation("TemplateStola");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.Stolica", b =>
                {
                    b.HasOne("EC.Domain.Data.Models.Sto", "Sto")
                        .WithMany()
                        .HasForeignKey("IdStola")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EC.Domain.Templates.TemplateStolice", "TemplateStolice")
                        .WithMany()
                        .HasForeignKey("IdTemplejtaStolice");

                    b.Navigation("Sto");

                    b.Navigation("TemplateStolice");
                });

            modelBuilder.Entity("EC.Domain.Data.Models.Totem", b =>
                {
                    b.HasOne("EC.Domain.Data.Models.EventCenter", "EventCentar")
                        .WithMany()
                        .HasForeignKey("EventCenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EC.Domain.Data.Models.Dogadjaj", "Dogadjaj")
                        .WithMany()
                        .HasForeignKey("IdDogadjaja");

                    b.Navigation("Dogadjaj");

                    b.Navigation("EventCentar");
                });

            modelBuilder.Entity("EC.Domain.Templates.TemplateStola", b =>
                {
                    b.HasOne("EC.Domain.Data.Models.MapaSedenja", "MapaSedenja")
                        .WithMany()
                        .HasForeignKey("IdMape")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapaSedenja");
                });

            modelBuilder.Entity("EC.Domain.Templates.TemplateStolice", b =>
                {
                    b.HasOne("EC.Domain.Templates.TemplateStola", "TemplateStola")
                        .WithMany()
                        .HasForeignKey("IdTemplejtaStola")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateStola");
                });
#pragma warning restore 612, 618
        }
    }
}
